IF OBJECT_ID('dbo.examSpEliminarUsuario') > 0
  DROP PROCEDURE dbo.examSpEliminarUsuario
GO

SET DATEFIRST 7
SET ANSI_NULLS ON
SET ANSI_WARNINGS ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT - 1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO

CREATE PROCEDURE [dbo].[examSpEliminarUsuario] @Nick varchar(250)
AS
BEGIN

	delete
	from examusuario2
	where Correo = @Nick



END